Bazel: "@net_zlib_zlib//:z" renamed to "@net_zlib_zlib//:zlib" to accord with rules_boost
```
Repository rule http_archive defined at:
  /home/story/.cache/bazel/_bazel_story/5f6cfd791ed6436cd7d0a9ad06515f99/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: /home/story/.cache/bazel/_bazel_story/5f6cfd791ed6436cd7d0a9ad06515f99/external/boost/BUILD.bazel:810:14: no such target '@net_zlib_zlib//:zlib': target 'zlib' not declared in package '' defined by /home/story/.cache/bazel/_bazel_story/5f6cfd791ed6436cd7d0a9ad06515f99/external/net_zlib_zlib/BUILD.bazel and referenced by '@boost//:iostreams'
```